### ISSUE TITLE
Add BACKSOLVED option to puzzle status

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#8] opened 2019-11-25 01:28 UTC
It could be helpful for reference when looking back on the hunt to know which puzzles we forward-solved vs. backsolved.

**Comment by alisonychang** [comment] 2019-12-02 04:23
As per discussion in group chat, leaning towards doing this via a tagging system where "backsolved" can be one of (possibly many) tags that we can then filter by. Prefer this over adding "backsolved" to the STATUS enum since a puzzle can be both SOLVED and backsolved.

**Comment by erwa** [comment] 2019-12-02 04:35
Filed #32 for general tagging functionality.

**Comment by asdfryan** [comment] 2019-12-03 19:59
Duplicate of #32

**Closed by asdfryan** 2019-12-03 19:59 UTC
