### ISSUE TITLE
Voice channel per puzzle

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/smallboard#185] opened 2020-11-01 21:14 UTC
Requested by Max -- this will be important when working remotely. They should be GC'ed once solved.

**Comment by akirabaruah** [comment] 2020-11-24 01:16
@rawxfish outlined a plan in https://github.com/cardinalitypuzzles/smallboard/issues/186#issuecomment-732468949

The current proposal for voice chat is to have a pool of voice channels and reuse them accordingly. As sushi mentioned, we should probably document a naming convention/policy for voice channels to keep things organized.

**Comment by rgossiaux** [comment] 2020-12-13 07:18
Duplicate of #186. Don't think this tracks anything different from that one.

**Comment by rgossiaux** [comment] 2020-12-13 07:19
Duplicate of #186

**Closed** 2020-12-13 07:19 UTC
