### ISSUE TITLE
Aggressively prune unused channels

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/smallboard#467] opened 2021-02-01 03:31 UTC
We should aggressively prune unused discord channels:
- Voice channels that contain 0 people, and for puzzles that are long-solved
- Text channels for puzzles that contain 0 non-automated messages and are long-solved

**Comment by rgossiaux** [comment] 2021-02-02 05:43
Duplicate of #414

**Closed by rgossiaux** 2021-02-02 05:43 UTC
Labels: discord integration
